import type { ElementDefinition, ElementGroup } from '@/types';

// ==================== HYROX STATIONS ====================
const hyroxStations: ElementDefinition[] = [
  {
    id: 'skierg',
    name: 'SkiErg',
    type: 'station',
    category: 'station',
    icon: 'stations/skierg',
    color: '#EF4444',
    defaultWidth: 100,
    defaultHeight: 100,
    exerciseType: 'skierg',
  },
  {
    id: 'sled-push',
    name: 'Sled Push',
    type: 'station',
    category: 'station',
    icon: 'stations/sled-push',
    color: '#EF4444',
    defaultWidth: 120,
    defaultHeight: 80,
    exerciseType: 'sled_push',
  },
  {
    id: 'sled-pull',
    name: 'Sled Pull',
    type: 'station',
    category: 'station',
    icon: 'stations/sled-pull',
    color: '#EF4444',
    defaultWidth: 120,
    defaultHeight: 80,
    exerciseType: 'sled_pull',
  },
  {
    id: 'burpee-broad-jump',
    name: 'Burpee Broad Jump',
    type: 'station',
    category: 'station',
    icon: 'stations/burpee-broad-jump',
    color: '#EF4444',
    defaultWidth: 140,
    defaultHeight: 60,
    exerciseType: 'burpee_broad_jump',
  },
  {
    id: 'rowing',
    name: 'Rowing',
    type: 'station',
    category: 'station',
    icon: 'stations/rowing',
    color: '#EF4444',
    defaultWidth: 100,
    defaultHeight: 100,
    exerciseType: 'rowing',
  },
  {
    id: 'farmers-carry',
    name: 'Farmers Carry',
    type: 'station',
    category: 'station',
    icon: 'stations/farmers-carry',
    color: '#EF4444',
    defaultWidth: 140,
    defaultHeight: 60,
    exerciseType: 'farmers_carry',
  },
  {
    id: 'lunges',
    name: 'Sandbag Lunges',
    type: 'station',
    category: 'station',
    icon: 'stations/lunges',
    color: '#EF4444',
    defaultWidth: 140,
    defaultHeight: 60,
    exerciseType: 'lunges',
  },
  {
    id: 'wall-balls',
    name: 'Wall Balls',
    type: 'station',
    category: 'station',
    icon: 'stations/wall-balls',
    color: '#EF4444',
    defaultWidth: 100,
    defaultHeight: 100,
    exerciseType: 'wall_balls',
  },
];

// ==================== ZONES ====================
const zones: ElementDefinition[] = [
  {
    id: 'start',
    name: 'Depart',
    type: 'zone',
    category: 'zone',
    icon: 'zones/start',
    color: '#22C55E',
    defaultWidth: 120,
    defaultHeight: 60,
  },
  {
    id: 'finish',
    name: 'Arrivee',
    type: 'zone',
    category: 'zone',
    icon: 'zones/finish',
    color: '#22C55E',
    defaultWidth: 120,
    defaultHeight: 60,
  },
  {
    id: 'spectators',
    name: 'Spectateurs',
    type: 'zone',
    category: 'zone',
    icon: 'zones/spectators',
    color: '#A855F7',
    defaultWidth: 160,
    defaultHeight: 100,
  },
  {
    id: 'warmup',
    name: 'Echauffement',
    type: 'zone',
    category: 'zone',
    icon: 'zones/warmup',
    color: '#F59E0B',
    defaultWidth: 160,
    defaultHeight: 100,
  },
  {
    id: 'water',
    name: 'Ravitaillement',
    type: 'zone',
    category: 'zone',
    icon: 'zones/water',
    color: '#3B82F6',
    defaultWidth: 80,
    defaultHeight: 80,
  },
  {
    id: 'parking',
    name: 'Parking',
    type: 'zone',
    category: 'zone',
    icon: 'zones/parking',
    color: '#6B7280',
    defaultWidth: 160,
    defaultHeight: 120,
  },
  {
    id: 'toilets',
    name: 'Toilettes',
    type: 'zone',
    category: 'zone',
    icon: 'zones/toilets',
    color: '#6B7280',
    defaultWidth: 80,
    defaultHeight: 80,
  },
  {
    id: 'podium',
    name: 'Podium / Scene',
    type: 'zone',
    category: 'zone',
    icon: 'zones/podium',
    color: '#F59E0B',
    defaultWidth: 140,
    defaultHeight: 80,
  },
];

// ==================== MARKERS ====================
const markers: ElementDefinition[] = [
  {
    id: 'cone',
    name: 'Cone',
    type: 'marker',
    category: 'marker',
    icon: 'markers/cone',
    color: '#F97316',
    defaultWidth: 30,
    defaultHeight: 30,
  },
  {
    id: 'barrier',
    name: 'Barriere',
    type: 'marker',
    category: 'marker',
    icon: 'markers/barrier',
    color: '#9CA3AF',
    defaultWidth: 120,
    defaultHeight: 20,
  },
  {
    id: 'distance',
    name: 'Distance',
    type: 'text',
    category: 'marker',
    icon: 'markers/distance',
    color: '#000000',
    defaultWidth: 80,
    defaultHeight: 30,
  },
  {
    id: 'text',
    name: 'Texte libre',
    type: 'text',
    category: 'marker',
    icon: 'markers/text',
    color: '#000000',
    defaultWidth: 120,
    defaultHeight: 40,
  },
];

// ==================== CROSSFIT ELEMENTS ====================
const crossfitElements: ElementDefinition[] = [
  {
    id: 'pullup-bar',
    name: 'Pull-up Bar / Rig',
    type: 'station',
    category: 'equipment',
    icon: 'crossfit/pullup-bar',
    color: '#8B5CF6',
    defaultWidth: 120,
    defaultHeight: 60,
    exerciseType: 'custom',
  },
  {
    id: 'box-jump',
    name: 'Box Jump',
    type: 'station',
    category: 'equipment',
    icon: 'crossfit/box-jump',
    color: '#8B5CF6',
    defaultWidth: 60,
    defaultHeight: 60,
    exerciseType: 'custom',
  },
  {
    id: 'kettlebell',
    name: 'Kettlebell',
    type: 'station',
    category: 'equipment',
    icon: 'crossfit/kettlebell',
    color: '#8B5CF6',
    defaultWidth: 50,
    defaultHeight: 50,
    exerciseType: 'custom',
  },
  {
    id: 'barbell',
    name: 'Barbell / Rack',
    type: 'station',
    category: 'equipment',
    icon: 'crossfit/barbell',
    color: '#8B5CF6',
    defaultWidth: 120,
    defaultHeight: 40,
    exerciseType: 'custom',
  },
  {
    id: 'assault-bike',
    name: 'Assault Bike',
    type: 'station',
    category: 'equipment',
    icon: 'crossfit/assault-bike',
    color: '#8B5CF6',
    defaultWidth: 80,
    defaultHeight: 80,
    exerciseType: 'custom',
  },
  {
    id: 'rope-climb',
    name: 'Corde a grimper',
    type: 'station',
    category: 'equipment',
    icon: 'crossfit/rope-climb',
    color: '#8B5CF6',
    defaultWidth: 40,
    defaultHeight: 100,
    exerciseType: 'custom',
  },
  {
    id: 'dumbbell',
    name: 'Dumbbell',
    type: 'station',
    category: 'equipment',
    icon: 'crossfit/dumbbell',
    color: '#8B5CF6',
    defaultWidth: 60,
    defaultHeight: 30,
    exerciseType: 'custom',
  },
  {
    id: 'ghd',
    name: 'GHD',
    type: 'station',
    category: 'equipment',
    icon: 'crossfit/ghd',
    color: '#8B5CF6',
    defaultWidth: 80,
    defaultHeight: 60,
    exerciseType: 'custom',
  },
];

// ==================== STRUCTURES / BARRIERES ====================
const structures: ElementDefinition[] = [
  {
    id: 'barrier-metal',
    name: 'Barriere metalique',
    type: 'barrier',
    category: 'structure',
    icon: '',
    color: '#6B7280',
    defaultWidth: 150,
    defaultHeight: 6,
    fillStyle: 'solid',
    strokeWidth: 6,
    showIcon: false,
  },
  {
    id: 'barrier-thin',
    name: 'Barriere fine',
    type: 'barrier',
    category: 'structure',
    icon: '',
    color: '#9CA3AF',
    defaultWidth: 120,
    defaultHeight: 3,
    fillStyle: 'solid',
    strokeWidth: 3,
    showIcon: false,
  },
  {
    id: 'barrier-thick',
    name: 'Mur / Cloison',
    type: 'barrier',
    category: 'structure',
    icon: '',
    color: '#374151',
    defaultWidth: 160,
    defaultHeight: 10,
    fillStyle: 'solid',
    strokeWidth: 10,
    showIcon: false,
  },
  {
    id: 'separator-dashed',
    name: 'Separateur pointille',
    type: 'barrier',
    category: 'structure',
    icon: '',
    color: '#D1D5DB',
    defaultWidth: 200,
    defaultHeight: 4,
    fillStyle: 'solid',
    strokeWidth: 4,
    dashPattern: [12, 6],
    showIcon: false,
  },
  {
    id: 'fence',
    name: 'Cloture / Grillage',
    type: 'barrier',
    category: 'structure',
    icon: '',
    color: '#92400E',
    defaultWidth: 180,
    defaultHeight: 5,
    fillStyle: 'solid',
    strokeWidth: 5,
    showIcon: false,
  },
  {
    id: 'zone-solid',
    name: 'Zone pleine',
    type: 'shape',
    category: 'structure',
    icon: '',
    color: '#3B82F6',
    defaultWidth: 160,
    defaultHeight: 100,
    fillStyle: 'solid',
    fillOpacity: 0.4,
    showIcon: false,
  },
  {
    id: 'zone-outline',
    name: 'Zone contour',
    type: 'shape',
    category: 'structure',
    icon: '',
    color: '#EF4444',
    defaultWidth: 160,
    defaultHeight: 100,
    fillStyle: 'none',
    strokeWidth: 3,
    showIcon: false,
  },
  {
    id: 'rectangle-solid',
    name: 'Rectangle plein',
    type: 'shape',
    category: 'structure',
    icon: '',
    color: '#10B981',
    defaultWidth: 120,
    defaultHeight: 80,
    fillStyle: 'solid',
    fillOpacity: 0.6,
    showIcon: false,
  },
  {
    id: 'circle-zone',
    name: 'Cercle',
    type: 'shape',
    category: 'structure',
    icon: '',
    color: '#8B5CF6',
    defaultWidth: 100,
    defaultHeight: 100,
    fillStyle: 'solid',
    fillOpacity: 0.4,
    shapeForm: 'circle',
    showIcon: false,
  },
  {
    id: 'diamond-zone',
    name: 'Losange',
    type: 'shape',
    category: 'structure',
    icon: '',
    color: '#F59E0B',
    defaultWidth: 100,
    defaultHeight: 100,
    fillStyle: 'solid',
    fillOpacity: 0.4,
    shapeForm: 'diamond',
    showIcon: false,
  },
  {
    id: 'hexagon-zone',
    name: 'Hexagone',
    type: 'shape',
    category: 'structure',
    icon: '',
    color: '#06B6D4',
    defaultWidth: 100,
    defaultHeight: 100,
    fillStyle: 'solid',
    fillOpacity: 0.4,
    shapeForm: 'hexagon',
    showIcon: false,
  },
  {
    id: 'triangle-zone',
    name: 'Triangle',
    type: 'shape',
    category: 'structure',
    icon: '',
    color: '#EF4444',
    defaultWidth: 100,
    defaultHeight: 100,
    fillStyle: 'solid',
    fillOpacity: 0.4,
    shapeForm: 'triangle',
    showIcon: false,
  },
];

// ==================== GROUPED LIBRARY ====================
export const elementLibrary: ElementGroup[] = [
  { name: 'Stations HYROX', category: 'station', elements: hyroxStations },
  { name: 'Zones', category: 'zone', elements: zones },
  { name: 'Structures / Barrieres', category: 'structure', elements: structures },
  { name: 'Marqueurs', category: 'marker', elements: markers },
  { name: 'CrossFit / Custom', category: 'equipment', elements: crossfitElements },
];

export const allElements: ElementDefinition[] = [
  ...hyroxStations,
  ...zones,
  ...structures,
  ...markers,
  ...crossfitElements,
];

export function getElementDefinition(id: string): ElementDefinition | undefined {
  return allElements.find((el) => el.id === id);
}
